name: Continuous Integration
on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        gnu-compiler-version:  [10, 11, 12]
    env:
      FC: gfortran-${{ matrix.gnu-compiler-version }}
      CC: gcc-${{ matrix.gnu-compiler-version }}
      FCFLAGS: "-ffree-line-length-none -m64 -std=f2008 -march=native -fbounds-check -finit-real=nan -g -DRTE_USE_CBOOL"
      NFHOME: /home/runner/netcdf-fortran
      RFMIP_DIR: /home/runner/rfmip-files
    steps:
    - name: Update system packages
      run: sudo apt-get update
    ############################################################################
    #
    # Compilers....
    #
    - name: install compilers
      run: sudo apt-get install gfortran-${{ matrix.gnu-compiler-version }} gcc-${{ matrix.gnu-compiler-version }}

    ############################################################################
    #
    # Netcdf C and Fortran
    #
    - name: Install HDF5 and netCDF libraries
      run: |
        sudo apt-get install libhdf5-dev libcurl4-gnutls-dev hdf5-helpers libnetcdf-dev
        dpkg -L libhdf5-dev libnetcdf-dev

    # Would be great to encode version info
    - name: cache-netcdf-fortran
      id: cache-netcdf-fortran
      uses: actions/cache@v2
      with:
        path: /home/runner/netcdf-fortran
        key: netcdf-fortran-4.5.3-${{ runner.os }}-${{ matrix.fortran-compiler }}

    - name: Build NetCDF Fortran library
      # Here too it would be nice to use the environment to specify netcdf-c location
      env:
        FCFLAGS: -fPIC
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        echo ${TEST}
        ${FC} --version
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.5.3
        cd netcdf-fortran
        echo ${CPPFLAGS}
        ./configure --prefix=${NFHOME}
        make -j
        sudo make install
    ############################################################################
    # Checks out repository under $GITHUB_WORKSPACE
    - name: Check out code
      uses: actions/checkout@v2

    - name: Environmental variables
      run: echo "RRTMGP_ROOT=${GITHUB_WORKSPACE}"        >> $GITHUB_ENV

    - name: Make library, examples, tests
      env:
        RTE_KERNELS: ${{ matrix.rte-kernels }}
      run: |
        cd ${RRTMGP_ROOT}
        ${FC} --version
        make libs
        make -C build separate-libs

    ############################################################################
    # Set up Python and packages
    #
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        activate-environment: rte_rrtmgp_test
        environment-file: environment.yml
        python-version: 3.9
        auto-activate-base: false
    ############################################################################
    - name: Cache RFMIP files
      id: cache-rfmip-files
      uses: actions/cache@v2
      with:
        path: /home/runner/rfmip-files # Same as #{RFMIP_DIR}
        key: rfmip-files

    - name: Stage RFMIP files
      if: steps.cache-rfmip-files.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${RFMIP_DIR}
        cd ${RFMIP_DIR}
        python ${RRTMGP_ROOT}/examples/rfmip-clear-sky/stage_files.py
    ############################################################################
    # Would be great to encode version info
    - name: Run examples, tests
      run: make tests

    - name: Comparison
      run: make check
